# Generated by Django 5.2.14 on 2026-06-25 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('deposit', '정기예금'), ('saving', '정기적금')], max_length=20)),
                ('dcls_month', models.CharField(blank=True, default='', max_length=6)),
                ('fin_co_no', models.CharField(max_length=30)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=200)),
                ('join_way', models.TextField(blank=True, default='')),
                ('mtrt_int', models.TextField(blank=True, default='')),
                ('spcl_cnd', models.TextField(blank=True, default='')),
                ('join_deny', models.IntegerField(blank=True, null=True)),
                ('join_member', models.TextField(blank=True, default='')),
                ('etc_note', models.TextField(blank=True, default='')),
                ('max_limit', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_type', 'kor_co_nm', 'fin_prdt_nm'],
                'constraints': [models.UniqueConstraint(fields=('product_type', 'fin_co_no', 'fin_prdt_cd'), name='unique_financial_product')],
            },
        ),
        migrations.CreateModel(
            name='FinancialOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(blank=True, default='', max_length=30)),
                ('intr_rate_type_nm', models.CharField(blank=True, default='', max_length=100)),
                ('rsrv_type', models.CharField(blank=True, default='', max_length=30)),
                ('rsrv_type_nm', models.CharField(blank=True, default='', max_length=100)),
                ('save_trm', models.PositiveIntegerField()),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='deposit.financialproduct')),
            ],
            options={
                'ordering': ['save_trm', '-intr_rate2'],
                'constraints': [models.UniqueConstraint(fields=('product', 'save_trm', 'intr_rate_type', 'rsrv_type'), name='unique_financial_option')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_financial_products', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_links', to='deposit.financialproduct')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_user_favorite_product')],
            },
        ),
    ]
