# Generated by Django 6.0.5 on 2026-05-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('annual_fee', models.CharField(max_length=100)),
                ('benefits', models.JSONField()),
                ('url', models.URLField()),
                ('card_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
