# Generated by Django 5.2.14 on 2026-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
                ('card_type', models.CharField(blank=True, default='', max_length=30)),
                ('target', models.CharField(blank=True, default='', max_length=50)),
                ('annual_fee', models.JSONField(blank=True, default=dict)),
                ('benefits', models.JSONField(blank=True, default=dict)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('detail_url', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['company', 'name'],
            },
        ),
    ]
