# Generated by Django 6.0.5 on 2026-05-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
